PL/Controllers/CorreoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http.Json;

namespace PL.Controllers
{
    //[Authorize]
    public class CorreoController : Controller
    {
        private readonly IHostEnvironment _hostEnvironment;

        private readonly BL.Correo _emailService;

        public CorreoController(IHostEnvironment hostEnvironment, BL.Correo emailService)
        {
            _hostEnvironment = hostEnvironment;

            _emailService = emailService;
        }

        [HttpGet]
        public IActionResult Correo()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Correo(string emailReceptor)
        {
            //Obtengo mi ruta de mi html
            string filePath = Path.Combine(_hostEnvironment.ContentRootPath, "Img", "PlantillaCorreo.html");

            //Enviar a mi metodo que lo lee
            string archivoHTMLLeido = BL.Correo.LeerHTML(filePath);

            try
            {
                string destinatario = "earredondo@digis01.com"; //Correo que recibe el mensaje
                string asunto = "Test de Envio de Correos"; //Asunto

                //Leo mi archivo html.
                string cuerpoHtml = archivoHTMLLeido;

                //string cuerpoHtml = "<h1>Este es un correo de prueba.</h1>" + "<p>Gracias.</p>"; //Plantilla html.

                var response = _emailService.EnviarCorreoAsync(destinatario, asunto, cuerpoHtml);

                return Ok("Correo enviado exitosamente.");
            }
            catch (Exception ex)
            {
                return StatusCode(500,"Error al enviar la notificación." + ex);
            }

        }

    }
}

PL/Controllers/EmpleadoAJAXController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class EmpleadoAJAXController : Controller
    {
        public IActionResult GetAllAJAX()
        {
            return View();
        }
    }
}

PL/Controllers/EmpleadoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{

    [Authorize(Roles = "Administrador")]
    public class EmpleadoController : Controller
    {
        private readonly IWebHostEnvironment _env;

        public EmpleadoController(IWebHostEnvironment env)
        {
            _env = env;
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            ML.Empleado empleado = new ML.Empleado();

            //ML.Result resultGetAll = BL.Empleado.GetAll();

            ML.Result resultGetAll = BL.Empleado.GetAllAPI();

            if (resultGetAll.Correct == true) 
            {
                empleado.Empleados = resultGetAll.Objects;
            }
            else
            {

            }

            return View(empleado);
        }

        [HttpGet]
        //[Authorize(Roles = "Administrador")]
        public IActionResult Form(int? IdEmpleado) 
        {
            ML.Empleado empleado = new ML.Empleado();

            if(IdEmpleado > 0) //Consulto mi usuario
            {
                ML.Result resultGetById = BL.Empleado.GetByIdAPI(IdEmpleado.Value);

                if (resultGetById.Correct == true)
                {
                    empleado = (ML.Empleado)resultGetById.Object;//Unboxing
                    ViewBag.Message = "Datos de Empleado cargados correctamente.";
                }
                else
                {
                    ViewBag.Message = "Error: No se pudo cargar el empleado solicitado.";
                }
            }
            else //Retorno la vista
            {
                
            }

            return View(empleado);
        }

        [HttpPost]
        public IActionResult Form(ML.Empleado empleado, IFormFile ImageFile)
        {
            ML.Empleado empleadoExistente = BL.Empleado.GetByIdImagen(empleado.IdEmpleado.Value);

            byte[] imagenActual = null;

            if(empleadoExistente.Imagen != null)
            {
                imagenActual = empleadoExistente.Imagen;
            }
            
            // Verificar si se subió un archivo
            if (ImageFile != null)
            {
                // Convertir IFormFile a byte[]
                using (var ms = new System.IO.MemoryStream())
                {
                    ImageFile.CopyTo(ms);
                    empleado.Imagen = ms.ToArray(); 
                }
            }
            else
            {
                if (imagenActual != null)
                {
                    empleado.Imagen = imagenActual;
                }
                else
                { 
                    //Obtengo la ruta de mi imagen por defecto.
                    var webRootPath = _env.ContentRootPath;
                    var defaultImagePath = Path.Combine(webRootPath, "wwwroot", "Img", "NoPhoto.png");

                    if (System.IO.File.Exists(defaultImagePath))
                    {
                        // Leer el archivo de imagen por defecto y convertirlo a byte[]
                        empleado.Imagen = System.IO.File.ReadAllBytes(defaultImagePath);
                    }
                }
            }

            if (empleado.IdEmpleado == 0) //Agrego
            {
                ML.Result resultAdd = BL.Empleado.AddAPI(empleado);

                if (resultAdd.Correct == true)
                {
                    return RedirectToAction("GetAll");
                }
                else
                {
                    ViewBag.Message = "Error: No se pudo guardar el empleado.";
                }
            }
            else //Actualizo
            {
                ML.Result resultUpdate = BL.Empleado.UpdateAPI(empleado);

                if(resultUpdate.Correct == true)
                {
                    return RedirectToAction("GetAll");
                }
                else
                {
                    ViewBag.Message = "Error: No se pudo actualizar el empleado solicitado.";
                }
            }

            return RedirectToAction("GetAll");
        }

        public IActionResult Delete(int IdEmpleado)
        {

            ML.Result resultDeleteEmpleado = BL.Empleado.DeleteAPI(IdEmpleado);

            if (resultDeleteEmpleado.Correct == true)
            {
                return RedirectToAction("GetAll");
            }
            else
            {

            }

            return RedirectToAction("GetAll");

        }
    }
}

PL/Controllers/PermisosController.cs
using Azure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using System.Net.Http;

namespace PL.Controllers
{
    
    public class PermisosController : Controller
    {
        [HttpGet]
        [Authorize(Roles = "Administrador")]
        public IActionResult GetAllSolicitudes()
        {
            #region CONSUMO DE SERVICIO GETALL

            ML.Result resultPermiso = new ML.Result();

            resultPermiso.Objects = new List<object>();

            //Recupero mi Token de mi Cookie
            string jwtToken = Request.Cookies["JwtToken"];

            using (var client = new HttpClient())
            {
                // Limpio las cabeceras
                client.DefaultRequestHeaders.Clear();

                // Añadir la cabecera Authorization con el prefijo "Bearer"
                client.DefaultRequestHeaders.Add("Authorization", $"Bearer {jwtToken}");

                client.BaseAddress = new Uri("http://localhost:5186/api/PermisoAPI/");
                var responseTask = client.GetAsync("GetAll");
                responseTask.Wait(); //peticion 
                var result = responseTask.Result; //guardo mi result

                if (result.IsSuccessStatusCode)
                {
                    //var readTask = result.Content.ReadAsAsync<ML.Result>(); 
                    var readTask = result.Content.ReadFromJsonAsync<ML.Result>(); //leo json y lo convierto a result
                    readTask.Wait();

                    foreach (var resultItem in readTask.Result.Objects)
                    {
                        ML.Permiso resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Permiso>(resultItem.ToString()); //deserealiza a mi modelo de Usuario
                        resultPermiso.Objects.Add(resultItemList);
                    }
                    resultPermiso.Correct = true;
                }
                else if (result.StatusCode == HttpStatusCode.Unauthorized || result.StatusCode == HttpStatusCode.Forbidden)
                {
                    // El token fue rechazado por la API (SL)
                    ViewBag.ErrorMessage = "El token no tiene permisos o expiró.";

                    // Opcional: Limpiar cookie y redirigir a login
                    return RedirectToAction("Login", "Usuario");
                }
                else
                {
                    resultPermiso.Correct = false;
                    resultPermiso.ErrorMessage = "No se encontraron permisos";
                }
            }

            #endregion

            ML.Permiso permiso = new ML.Permiso();

            if (resultPermiso.Correct == true)
            {
                permiso.Permisos = resultPermiso.Objects;
            }

            return View(permiso);
        }

        [HttpGet]
        [Authorize(Roles = "Administrador,Empleado")]
        public IActionResult SolicitudForm()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Administrador,Empleado")]
        public IActionResult SolicitudForm(ML.Permiso permiso)
        {
            // 1. Obtiene el DateTime del día de hoy
            DateTime hoy = DateTime.Today;

            // 2. Convierte el DateTime a DateOnly
            permiso.FechaSolicitud = DateOnly.FromDateTime(hoy);

            permiso.Empleado = new ML.Empleado();
            permiso.Empleado.IdEmpleado = 6;

            permiso.StatusPermiso = new ML.StatusPermiso();
            permiso.StatusPermiso.IdStatusPermiso = 1;

            #region CONSUMO DE SERVICIO ADD

            ML.Result resultAddAPI = new ML.Result();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:5186/api/PermisoAPI/");

                //HTTP POST
                var postTask = client.PostAsJsonAsync<ML.Permiso>("Add", permiso); //Serializar
                postTask.Wait();
                var resultPeticionPost = postTask.Result;

                if (resultPeticionPost.IsSuccessStatusCode)
                {
                    var readTask = resultPeticionPost.Content.ReadFromJsonAsync<ML.Result>();
                    readTask.Wait();

                    resultAddAPI.Object = readTask.Result;
                    resultAddAPI.Correct = true;
                }
                else
                {
                    resultAddAPI.Correct = false;
                    resultAddAPI.ErrorMessage = "No se pudo agregar el permiso";
                }
            }

            #endregion

            if (resultAddAPI.Correct == true)
            {
                return RedirectToAction("GetAllSolicitudes");
            }
            return View(permiso);
        }

        [Authorize(Roles = "Administrador")]
        public IActionResult ActualizarStatus(int? IdPermiso, byte? IdStatusPermiso)
        {
            ML.Permiso permiso = new ML.Permiso();

            permiso.IdPermiso = IdPermiso;
            permiso.StatusPermiso = new ML.StatusPermiso();
            permiso.StatusPermiso.IdStatusPermiso = IdStatusPermiso;
            
            if(IdStatusPermiso == 2) //Aprobado
            {
                permiso.IdAutorizador = 7;
            }
            else //Rechazado
            {
                permiso.IdAutorizador = 18;
            }

            #region CONSUMO DE SERVICIO UPDATE

            ML.Result resultUpdateAPI = new ML.Result();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:5186/api/PermisoAPI/");

                //HTTP Patch
                var postTask = client.PatchAsJsonAsync<ML.Permiso>("Update", permiso); //Serializar
                postTask.Wait();
                var resultPeticionPost = postTask.Result;

                if (resultPeticionPost.IsSuccessStatusCode)
                {
                    var readTask = resultPeticionPost.Content.ReadFromJsonAsync<ML.Result>();
                    readTask.Wait();

                    resultUpdateAPI.Object = readTask.Result;
                    resultUpdateAPI.Correct = true;

                }
                else
                {
                    resultUpdateAPI.Correct = false;
                    resultUpdateAPI.ErrorMessage = "No se pudo actualizar el registro.";
                }
            }

            #endregion

            if (resultUpdateAPI.Correct == true)
            {
                return RedirectToAction("GetAllSolicitudes");
            }

            return RedirectToAction("GetAllSolicitudes");

        }

        [HttpGet]
        [Authorize(Roles = "Administrador,Empleado")]
        public IActionResult HistorialPermisos()
        {
            #region CONSUMO DE SERVICIO GETALLHistorialPermisos

            ML.Result resultHistorialPermisos = new ML.Result();

            resultHistorialPermisos.Objects = new List<object>();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:5186/api/PermisoAPI/");
                var responseTask = client.GetAsync("GetAll/HistorialPermisos");
                responseTask.Wait(); //peticion 
                var result = responseTask.Result; //guardo mi result

                if (result.IsSuccessStatusCode)
                { 
                    var readTask = result.Content.ReadFromJsonAsync<ML.Result>(); //leo json y lo convierto a result
                    readTask.Wait();

                    foreach (var resultItem in readTask.Result.Objects)
                    {
                        ML.HistorialPermiso resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.HistorialPermiso>(resultItem.ToString()); //deserealiza a mi modelo de Usuario
                        resultHistorialPermisos.Objects.Add(resultItemList);
                    }
                    resultHistorialPermisos.Correct = true;
                }
                else
                {
                    resultHistorialPermisos.Correct = false;
                    resultHistorialPermisos.ErrorMessage = "No se encontro historial de permisos.";
                }
            }

            #endregion

            ML.HistorialPermiso historialPermiso = new ML.HistorialPermiso();   

            if (resultHistorialPermisos.Correct == true)
            {
                historialPermiso.ListaHistorialPermisos = resultHistorialPermisos.Objects;
            }

            return View(historialPermiso);
        }

    }
}

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*   Verifico si mi usuario esta autenticado, si no, muestro la interfaz del Login *@
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Empleado" asp-action="GetAll">Empleados C#</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="EmpleadoAJAX" asp-action="GetAllAJAX">Empleados AJAX</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Permisos" asp-action="SolicitudForm">Solicitar Permiso</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Permisos" asp-action="GetAllSolicitudes">Ver Permisos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Permisos" asp-action="HistorialPermisos">Historial Permisos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Correo" asp-action="Correo">Envio de Correos</a>
                            </li>
                            <li class="nav-item ms-auto">
                                @Html.ActionLink("Cerrar Sesión", "Logout", "Usuario", null, new { @class = "btn btn-outline-danger" })
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>